server:
  port: 8100

spring:
  application:
    name: zuul # 유레카에 등록할 서비스의 논리 이름
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
  jwt:
    secret: ${JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*' # 유레카 서비스 ID 기반의 모든 경로 등록 제외
#  prefix: /api        # 정의한 모든 서비스에 /api 접두어가 경로에 붙음
  routes:             # 엔드포인트 매핑
    auth:
      stripPrefix: false
      path: /auth/**
      serviceId: auth
      url: http://localhost:8080
    membership:
      stripPrefix: false
      path: /membership/**
      serviceId: membership
      url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: 'routes'
